version: '3.5'

services:
  server:
    image: ghcr.io/animo/reclaim/server:main
    deploy:
      labels:
        # Enable traefik so the container can be exposed to the outside world
        traefik.enable: 'true'

        # AFJ Rest agent inbound transport
        traefik.http.routers.reclaim-server-didcomm.rule: Host(`didcomm.reclaim.animo.id`)
        traefik.http.routers.reclaim-server-didcomm.entrypoints: web-secure
        traefik.http.routers.reclaim-server-didcomm.tls.certresolver: zerossl
        traefik.http.routers.reclaim-server-didcomm.service: reclaim-server-didcomm-service
        traefik.http.services.reclaim-server-didcomm-service.loadbalancer.server.port: 5001

        # AFJ Rest API
        traefik.http.routers.reclaim-server-rest.rule: Host(`server.reclaim.animo.id`)
        traefik.http.routers.reclaim-server-rest.entrypoints: web-secure
        traefik.http.routers.reclaim-server-rest.tls.certresolver: zerossl
        traefik.http.routers.reclaim-server-rest.service: reclaim-server-rest-service
        traefik.http.services.reclaim-server-rest-service.loadbalancer.server.port: 5000
    environment:
      AGENT_ENDPOINT: https://didcomm.reclaim.animo.id
      AGENT_PUBLIC_DID_SEED: ${AGENT_PUBLIC_DID_SEED}
      AGENT_WALLET_KEY: ${AGENT_WALLET_KEY}
    ports:
      - 5000
      - 5001
    networks:
      - traefik

  client:
    image: ghcr.io/animo/reclaim/client:main
    deploy:
      labels:
        # Enable traefik so the container can be exposed to the outside world
        traefik.enable: 'true'

        # AFJ Rest agent inbound transport
        traefik.http.routers.reclaim-frontend.rule: Host(`reclaim.animo.id`)
        traefik.http.routers.reclaim-frontend.entrypoints: web-secure
        traefik.http.routers.reclaim-frontend.tls.certresolver: zerossl
        traefik.http.routers.reclaim-frontend.service: reclaim-frontend-service
        traefik.http.services.reclaim-frontend-service.loadbalancer.server.port: 80
    networks:
      - traefik
    ports:
      - 80

networks:
  traefik:
    external: true
    name: traefik